### PR TITLE
Upgrades and fixes

### PR DESCRIPTION
**Pull request by hansmbakker**
##  Pull Request Type
[ ] Bugfix <!—Please add link to related Issue below -->  
[ ] New Sample  
[x] Other - Please describe:   updates and fixes

## Proposed Changes

- Retarget Visual Studio PlatformToolset to v141
- Retarget Windows SDK to 17763
- Update NuGet packages to most recent version
- Add SamplesNative to EffectEditor Project (compile fix)
- (added) compile fix by @daneuber

### CODE REVIEW

**Comment by daneuber** [comment]
@hansmbakker were you able to get the effect editor running with these changes alone? It's been a while since we updated and when I tested locally I also had to update some ImageLoader calls: [diff.txt](https://github.com/Microsoft/WindowsCompositionSamples/files/2480369/diff.txt)

**Comment by daneuber** [comment]
@hansmbakker ahh I see. If you could just add to your PR that'd be great!

**Comment by hansmbakker** [comment]
@daneuber I tried; after adding your fixes the code compiles but I get a runtime error at https://github.com/Microsoft/WindowsCompositionSamples/blob/master/SamplesCommon/SamplesCommon/ImageLoader/ImageLoader.cs#L112

Does this work for you?

I'm using Visual Studio 15.9 Preview 3 with SDK 177663.

The relevant parts of the logging are:
```
Error: Converter failed to convert value of type 'EffectEditor.MainPage.EffectType' to type 'Int32'; BindingExpression: Path='ActiveEffectType' DataItem='EffectEditor.MainPage'; target element is 'Windows.UI.Xaml.Controls.ComboBox' (Name='EffectSelector'); target property is 'SelectedIndex' (type 'Int32'). 
'EffectEditor.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\hansm\Source\Repos\WindowsCompositionSamples\Demos\EffectEditor\bin\x86\Debug\AppX\SamplesCommon.dll'. Symbols loaded.
'EffectEditor.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\hansm\Source\Repos\WindowsCompositionSamples\Demos\EffectEditor\bin\x86\Debug\AppX\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at SamplesCommon.ImageLoader.get_Instance()
   at EffectEditor.MainPage.CreateBrushFromAsset(String name, Size& size)
   at EffectEditor.MainPage.MainGridLoaded(Object sender, RoutedEventArgs e)
```

**Comment by daneuber** [comment]
Apologies, that's my fault for putting the ImageLoader Initialization in the CreateBrushFromAsset method which gets called multiple times. Here is a small diff moving that which should fix that error. Let me know if this fixes on your end as well. - [diff2.txt](https://github.com/Microsoft/WindowsCompositionSamples/files/2480586/diff2.txt)

**Comment by hansmbakker** [comment]
@daneuber thank you! Now it seems to work correctly 😃

**Comment by daneuber** [comment]
@hansmbakker  Awesome! Thanks for these changes!

**Comment by hansmbakker** [comment]
No problem, glad it's fixed :)

**Pull request merged**
