### PR TITLE
Some details fix

### PR DESCRIPTION
**Pull request by HO-COOH**
##  Pull Request Type
[x] Bugfix <!—Please add link to related Issue below -->  
[ ] New Sample  
[ ] Other - Please describe:   

## Issue
- Fixed: Text are not readable with dark theme
- Fixed: Shy header not responsive to wide screen

## Proposed Changes
-  
-

### CODE REVIEW

**Comment by jeffstall** [comment]
Can you actually migrate this to https://github.com/microsoft/WindowsAppSDK-Samples instead? We're in the process of consolidating repos to simplify things. This repo will be archived.

**Comment by HO-COOH** [comment]
@jeffstall I didn't see composition gallery's code anywhere in that repo. Maybe you should first update your contribution guide.

**Comment by jeffstall** [comment]
Hi @HO-COOH,

Thank-you for helping to make our samples better. Honestly, I really appreciate the help! Yes, we've been a little busy with cleaning everything up as part of Build 2024 and follow-up WinUI Community Call, which we just had this morning. The Compositions samples are [here](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/SceneGraph).

I have a list of things that we're working through on cleaning up and consolidating multiple repos together to make it much easier for Windows app development. I'm working with a few people in the process of cleaning up this repo, and we're getting ready to post updates in a week or two. I appreciated your fix, and I didn't want it to get lost in the process. 😅

Thanks for helping!
~ Jeffrey

**Comment by HO-COOH** [comment]
@jeffstall Sure. I just happened to look into Composition a lot lately. You can close it after your repo migration ready and I can resubmit them. I have some other features I want to contribute as well, and I will hold it back for now.

**Comment by jeffstall** [comment]
We're archiving this repo and have moved everything to https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/SceneGraph instead.

**Pull request closed without merging**
